export const sources=[
{id:'S1',publisher:'Course assignment',title:'Lesson 06 — Build a DataCenter Challenge',url:'https://docs.google.com/document/d/15disR3SYVSCnQtf4e_JU2cu2b7DoasymF_p08tpOjjI/edit',period:'Assignment brief',notes:'Starting facts and required deliverables; project commitments and tariffs are unknown.'},
{id:'S2',publisher:'DESNZ',title:'Digest of UK Energy Statistics 2025, chapters 1–7',url:'https://assets.publishing.service.gov.uk/media/68dbe477ef1c2f72bc1e4c4d/DUKES_2025_Chapters_1-7.pdf',period:'2024 / 2025 edition',notes:'UK renewable generation share reported as 50.4%. Historical edition, not a site-specific or hourly supply claim; later revisions may differ.'},
{id:'S3',publisher:'University of Bristol',title:'Isambard-AI launch',url:'https://www.bristol.ac.uk/news/2025/july/isambard-launch.html',period:'17 July 2025',notes:'Existing UK research-compute alternative. Access, allocations and workload fit must be confirmed; not assumed to be free or available.'},
{id:'S4',publisher:'Bristol Centre for Supercomputing',title:'Isambard system specifications',url:'https://docs.isambard.ac.uk/specs/',period:'Documentation accessed 5 October 2026',notes:'5,448 GH200 superchips. Hardware differs from this illustrative generic GPU fleet; performance is not interchangeable.'},
{id:'S5',publisher:'US Energy Information Administration',title:'US energy facts: 2024 data',url:'https://www.eia.gov/energyexplained/us-energy-facts/data-and-statistics.php',period:'2024, preliminary in cited edition',notes:'Electricity: 43% natural gas, 23% renewables, 18% nuclear. Country totals do not establish a local tariff or grid connection.'},
{id:'S6',publisher:'NESO and Carbon Intensity partners',title:'Great Britain Carbon Intensity API',url:'https://api.carbonintensity.org.uk/',period:'Half-hourly',notes:'GB, not the whole UK. Forecast/actual distinguished. A single interval must not be multiplied into an annual emissions claim.'},
{id:'S7',publisher:'GASTAT',title:'Electrical Energy Statistics 2024',url:'https://www.stats.gov.sa/en/w/electrical-energy-statistics-2024',period:'2024',notes:'Research lead only: detailed values not independently retrieved in this build. No unsupported numeric values entered.'}
];
export const claims=[
{id:'C1',type:'fact',text:'The proposal is for 25 MW of total site electrical demand, including cooling.',source:'S1',status:'Brief fact'},
{id:'C2',type:'fact',text:'No member has signed a long-term computing commitment; grid price, upgrades and energisation date are unknown.',source:'S1',status:'Unresolved investment gate'},
{id:'C3',type:'assumption',text:'UK Midlands is an illustrative search region, not a selected or secured site. 20 MW IT at PUE 1.25 forms the reference design.',source:'S1',status:'Planning assumption'},
{id:'C4',type:'calculation',text:'At the baseline, 20 MW × 1.25 = 25 MW; 25 × 8,760 / 1,000 = 219 GWh/year at continuous design load.',source:'S1',status:'Deterministic'},
{id:'C5',type:'assumption',text:'16,000 benchmark-equivalent GPUs; £25,000 per GPU including host share; 65% productive utilisation. These are estimates, not demand evidence or supplier quotes.',source:null,status:'Validate with benchmarks and contracts'},
{id:'C6',type:'design_decision',text:'Lease first; retain an option for a 10 MW facility and 6,400 GPUs. Authorise construction only after contracted demand, grid and cost gates pass.',source:null,status:'Conditional recommendation'},
{id:'C7',type:'fact',text:'The cited DUKES 2025 edition reports 50.4% renewable electricity generation in 2024. This does not prove 24/7 carbon-free power for the proposed site.',source:'S2',status:'Historical evidence'},
{id:'C8',type:'fact',text:'Isambard-AI launched in Bristol in July 2025 and is part of the UK AI Research Resource, alongside Dawn.',source:'S3',status:'Existing alternative'},
{id:'C9',type:'unknown',text:'There is no binding utility offer, parcel-specific carbon profile, water permit, construction quote or signed membership allocation.',source:'S1',status:'Evidence required'},
{id:'C10',type:'assumption',text:'Target 99.95% service availability for teaching/inference and checkpointed batch training. N+1 backup and two power paths remain unverified concepts.',source:null,status:'Engineer validation required'},
{id:'C11',type:'assumption',text:'No solar, wind or gas generation receives firm-capacity credit. A UPS bridges transfer only; diesel backup is sized for a 48-hour outage conceptually.',source:null,status:'Hourly resilience studies required'},
{id:'C12',type:'unknown',text:'Comparable counts of operational datacentres and installed IT capacity for all three countries have not been verified. Missing values are null, never zero.',source:null,status:'Research gap'}
];
export const countries=[
{id:'UK',name:'United Kingdom',region:'Midlands (illustrative)',mix:'50.4% renewable generation',vintage:'2024, DUKES 2025 edition',source:'S2',rationale:'Preferred for this UK consortium: research collaboration, local operations and reduced cross-border complexity. Exact site remains open.',water:'Dry coolers with closed-loop liquid cooling proposed; heatwave derating and water for exceptional operation require a local study.',alternative:'Isambard-AI / Dawn allocations and existing UK colocation; availability must be negotiated.',dcCount:null,capacity:null,carbon:null},
{id:'US',name:'United States',region:'Region not selected',mix:'43% gas · 23% renewable · 18% nuclear',vintage:'2024, EIA cited preliminary edition',source:'S5',rationale:'Candidate for burst capacity; validate data-transfer permissions, latency, egress, benchmark equivalence and regional availability.',water:'Cooling and water exposure vary by basin and climate. No national average is a substitute for site permits.',alternative:'Commercial on-demand compute; obtain region-specific quotes and workload benchmarks.',dcCount:null,capacity:null,carbon:null},
{id:'SA',name:'Saudi Arabia',region:'Region not selected',mix:'Not verified in this evidence set',vintage:'2024 publication identified; detailed values pending',source:'S7',rationale:'Comparator requiring validated tariffs, compute availability, data-transfer review and climate-specific engineering.',water:'Use a hot-weather dry-cooling scenario; validate design wet/dry bulb, derating and water availability locally.',alternative:'Regional providers and research institutions; capacity and eligibility unconfirmed.',dcCount:null,capacity:null,carbon:null}
];
export const requirements=[
['Training researchers','55.0m GPU-h / year','Large contiguous jobs; overnight and weekends','Checkpoint every 15 minutes; reserved multi-node blocks; tenant isolation'],
['Teaching & smaller institutions','20.0m GPU-h / year','Term-time daytime peaks','99.95% service target; 20% protected allocation pool; per-course quotas'],
['Inference & applied research','16.104m GPU-h / year','Steady services plus bursts','99.95% service target; encrypted storage; UK placement for restricted datasets']
];
export const gates=[['Demand','At least 70% of the 10 MW module’s 42m annual productive GPU-hours contracted for 3+ years; benchmark workload equivalence.','Consortium members','Not met'],['Power','Binding grid capacity, total tariff, upgrade scope and energisation milestones; independently reviewed N−1 study.','Utility + consortium','Not met'],['Economics','Fixed-scope bids and benchmarked lease quotes; hybrid total cost acceptable under delay and half-demand cases.','Board + independent cost adviser','Not met']];
export const financing=[['Development equity','Capped £2m feasibility mandate within the facility allowance; parcel shortlist, demand survey, grid study and exit rights.','Members bear the capped development loss; no construction guarantee.'],['Construction debt','Binding connection agreement, permits, fixed-scope EPC contract, signed take-or-pay demand, contingency, insurance and lender technical review.','Consortium SPV bears residual delay; EPC/utility remedies only where contracted. Delay bridge lease and interest are modelled.'],['GPU procurement / equipment finance','Acceptable benchmarks, delivery tied to energisation, warranty/support, refresh plan and funded reservations.','Base model cash-buys GPUs. If financed, members/SPV bear residual-value and obsolescence risk; require a separate lender quote.']];
export const governance=[['Ownership','A university-owned special-purpose entity owns land rights, electrical/cooling plant, shared fabric/storage and the minimum committed GPU fleet.'],['Contracts','Tender design/build, maintenance, electricity, fibre, hardware support and burst compute. Ring-fence facility accounts from GPU refresh reserves.'],['Allocation','Proposed split: 60% contracted reservations, 20% peer-reviewed research, 20% teaching/small-member pool. Idle reservations return to a common queue.'],['Pricing','Publish a two-part tariff: fixed reservation charges plus metered energy/compute. No hidden subsidy from non-users; annual independent cost reconciliation.'],['Fair access','No member may consume over 25% of the shared pool without board approval. Per-project quotas, weighted fair queues and teaching windows apply.'],['Oversight','One institutional vote per member; small-member representation; independent conflict appeal. Publish utilisation and wait-time reports quarterly.'],['Withdrawal','Require notice, take-or-pay exit payments and credit support; no automatic transfer of the shortfall to smaller members. Suspend expansion if coverage fails.']];
