import {sqliteTable,text,integer,real,index} from 'drizzle-orm/sqlite-core';
export const users=sqliteTable('users',{id:text('id').primaryKey(),email:text('email'),team:text('team').notNull(),role:text('role').notNull().default('viewer'),registeredAt:text('registered_at').notNull()});
export const countries=sqliteTable('countries',{id:text('id').primaryKey(),name:text('name').notNull(),data:text('data').notNull()});
export const sources=sqliteTable('sources',{id:text('id').primaryKey(),publisher:text('publisher').notNull(),title:text('title').notNull(),url:text('url').notNull(),period:text('period'),notes:text('notes'),accessedAt:text('accessed_at').notNull()});
export const designs=sqliteTable('designs',{id:integer('id').primaryKey(),country:text('country').notNull(),assumptions:text('assumptions').notNull(),updatedAt:text('updated_at').notNull()});
export const claims=sqliteTable('design_claims',{id:text('id').primaryKey(),designId:integer('design_id').notNull().references(()=>designs.id),type:text('claim_type').notNull(),text:text('claim_text').notNull(),sourceId:text('source_id').references(()=>sources.id),status:text('status').notNull(),updatedAt:text('updated_at').notNull()},t=>[index('idx_claims_design').on(t.designId)]);
export const metrics=sqliteTable('metrics',{id:integer('id').primaryKey({autoIncrement:true}),country:text('country_id').notNull().references(()=>countries.id),name:text('metric_name').notNull(),value:real('value'),unit:text('unit').notNull(),period:text('reporting_period').notNull(),source:text('source_id').notNull().references(()=>sources.id),retrievedAt:text('retrieved_at').notNull(),notes:text('notes')},t=>[index('idx_metrics_country_name').on(t.country,t.name)]);
export const requests=sqliteTable('ai_requests',{id:text('id').primaryKey(),userId:text('user_id').notNull(),createdAt:text('created_at').notNull()},t=>[index('idx_requests_user_time').on(t.userId,t.createdAt)]);
export const decisions=sqliteTable('decisions',{id:text('id').primaryKey(),userId:text('user_id').notNull(),decision:text('decision').notNull(),reason:text('reason').notNull(),createdAt:text('created_at').notNull()});
